INSERT INTO `categories` (`category_id`, `category`)
VALUES
       (3, 'Books'),
       (4, 'Car'),
       (5, 'Clothes'),
       (6, 'Cosmetics'),
       (7, 'Eating Out'),
       (8, 'Education'),
       (9, 'Electronics'),
       (10, 'Entertainment'),
       (11, 'Fuel'),
       (12, 'Gifts to Others'),
       (25, 'Groceries'),
       (13, 'Home'),
       (16, 'Medicine'),
       (18, 'Recreational'),
       (19, 'Religion'),
       (20, 'Subscriptions'),
       (21, 'Transportation'),
       (23, 'Utilities'),
       (24, 'Work');


INSERT INTO `descriptions` (`description`, `category`)
VALUES ('AL MAAS INDIAN FAMILY R', 'Eating Out'),
       ('ARPICO', 'Groceries'),
       ('ARTHUR\'S PIZZA', 'Eating Out'),
       ('BARISTA', 'Eating Out'),
       ('BOOK MY SHOW', 'Recreational'),
       ('CARAVAN FRESH', 'Eating Out'),
       ('CARAVAN FRESH - KIRULAP', 'Eating Out'),
       ('CARAVAN FRESH - MAHARAG', 'Eating Out'),
       ('CARGILLS', 'Groceries'),
       ('CHOLA RESTAURANTS', 'Eating Out'),
       ('Cool Planet - Maharagam', 'Clothes'),
       ('Dentz Avenue (PVT) Ltd', 'Medicine'),
       ('DEPRTMNT OF MOTOR TRFFI', 'Transportation'),
       ('Dialog Axiata PLC', 'Utilities'),
       ('DOMINOS PIZZA', 'Eating Out'),
       ('EXCEL RESTAURANT', 'Recreational'),
       ('FAB FOOD (PVT) LTD', 'Eating Out'),
       ('FRESHMA FLORA', 'Recreational'),
       ('FUEL STATION', 'Fuel'),
       ('GIGA FOODS', 'Eating Out'),
       ('Google YouTube', 'Subscriptions'),
       ('INTERCHANGE', 'Transportation'),
       ('KEELLS', 'Groceries'),
       ('LANKA FILLING', 'Fuel'),
       ('MILLENNIUM FOOD CENTRE', 'Eating Out'),
       ('P AND B FUEL MART', 'Fuel'),
       ('PAYPAL *QUILLBOT', 'Work'),
       ('PERERA & SONS BAKERS (P', 'Eating Out'),
       ('PickMe Food', 'Eating Out'),
       ('PickMe Ride', 'Transportation'),
       ('PIZZA HUT', 'Eating Out'),
       ('ROAD DEVELOPMENT AUTHOR', 'Transportation'),
       ('SEVEN 10 CAR CARE', 'Car'),
       ('SIRILAK SEA FOOD', 'Groceries'),
       ('SPAR', 'Groceries'),
       ('STREET BURGER - MAHARAG', 'Eating Out'),
       ('SUBWAY', 'Eating Out'),
       ('SUPER K-PILIYANDALA', 'Groceries'),
       ('T AND S FUEL MART', 'Fuel'),
       ('TACO BELL', 'Eating Out'),
       ('THE FAB', 'Eating Out'),
       ('UBER EATS', 'Eating Out');

